import {OverProtectionType} from '../sdk/MPSDKDefines';

export type RootStackParamList = {
  Scan: undefined;
  MainTabs: undefined;
  SwitchSettings: undefined;
  ElectricitySettings: undefined;
  EnergySettings: undefined;
  ProtectionSettings: undefined;
  OverProtection: {type: OverProtectionType};
  LoadStatusNotification: undefined;
  CountdownSettings: undefined;
  LEDSettings: undefined;
  PowerIndicatorColor: undefined;
  LoRaSettings: undefined;
  LoRaApp: undefined;
  Downlink: undefined;
  OutdoorFix: undefined;
  LCGpsFix: undefined;
  BleFix: undefined;
  OnOffSettings: undefined;
  BleSettings: undefined;
  DeviceInfo: undefined;
  BatteryConsumption: undefined;
  Update: undefined;
  Debugger: {macAddress?: string} | undefined;
  FilterByRawData: undefined;
  FilterByBeacon: {variant: 'beacon' | 'bxp'};
  FilterByUID: undefined;
  FilterByURL: undefined;
  FilterByTLM: undefined;
  FilterByBXPButton: undefined;
  FilterByBXPTag: undefined;
  FilterByPir: undefined;
  FilterByTof: undefined;
  FilterByOther: undefined;
  FilterByMac: undefined;
  FilterByAdvName: undefined;
  About: undefined;
  DeviceMode: undefined;
  StandbyMode: undefined;
  PeriodicMode: undefined;
  TimingMode: undefined;
  MotionMode: undefined;
  TimeSegmentedMode: undefined;
  Vibration: undefined;
  Auxiliary: undefined;
  AxisSetting: undefined;
  AlertAlarmSettings: undefined;
  SosAlarmSettings: undefined;
  LightMonitorSettings: undefined;
  TempMonitorSettings: undefined;
  IndicatorSettings: undefined;
  LocalDataSync: undefined;
  ManDown: undefined;
  TamperAlarm: undefined;
  AlarmFunction: undefined;
  Battery: undefined;
  System: undefined;
};

export type MainTabParamList = {
  LORA: undefined;
  GENERAL: undefined;
  BLUETOOTH: undefined;
  DEVICE: undefined;
};
